### ISSUE TITLE
ImproperlyConfigured: 'django_cockroachdb' isn't an available database backend.

### ISSUE THREAD

**Issue by Alir3z4** [cockroachdb/django-cockroachdb#190]
I tried to run `./manage.py migrate` and got the following error.

Error:
```
Traceback (most recent call last):
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django_cockroachdb/__init__.py", line 2, in <module>
    from .lookups import patch_lookups
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django_cockroachdb/lookups.py", line 1, in <module>
    from django.db.models.fields.json import HasKeyLookup, KeyTransform
MuleNotFouodndError: No module named 'django.db.models.fields.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/db/models/base.py", line 121, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/db/models/options.py", line 208, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/db/utils.py", line 207, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/alireza/.virtualenvs/jobjoob/lib/python3.8/site-packages/django/db/utils.py", line 122, in load_backend
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: 'django_cockroachdb' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```

Although from the the traceback
```
MuleNotFouodndError: No module named 'django.db.models.fields.json'
```

Has been reported as well. my app uses JSONField as well.

**Comment by timgraham** [comment]
It looks like you're using the wrong version of django-cockroachdb for your version of Django.  Please follow the README Instructions:

Use the version of django-cockroachdb that corresponds to your version of Django. For example, to get the latest compatible release for Django 3.1.x:
```
pip install django-cockroachdb==3.1.*
```
The minor release number of Django doesn't correspond to the minor release number of django-cockroachdb. Use the latest minor release of each.
