### ISSUE TITLE
Package build fails with "No module named 'django'"

### ISSUE THREAD

**Issue by piotrb5e3** [cockroachdb/django-cockroachdb#246]
`django-cockroachdb` fails to build when installed from remote VCS with pip. The error is
```
ModuleNotFoundError: No module named 'django'
```
Looks like this is caused by `check_django_compatability()`, which is run every time the package is imported.
Unfortunately setuptools imports the package during build, before our other dependencies (including `django`) are installed.
Adding `django` as a setup dependency solves the problem.

**Comment by timgraham** [comment]
You might find this is resolved if you upgrade setuptools. I observed with setuptools 44.1.1:
```
$ pip install -e ~/code/cockroach-django/
Obtaining file:///home/tim/code/cockroach-django
    ERROR: Command errored out with exit status 1:
     command: /home/tim/.virtualenvs/tmp-c0a4a8105a1aa839/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/tim/code/cockroach-django/setup.py'"'"'; __file__='"'"'/home/tim/code/cockroach-django/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cdqfqapc
         cwd: /home/tim/code/cockroach-django/
    Complete output (37 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/tim/code/cockroach-django/setup.py", line 3, in <module>
        setup()
      File "/home/tim/.virtualenvs/tmp-c0a4a8105a1aa839/lib/python3.8/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/home/tim/.virtualenvs/tmp-c0a4a8105a1aa839/lib/python3.8/site-packages/_virtualenv.py", line 21, in parse_config_files
        result = old_parse_config_files(self, *args, **kwargs)
      File "/home/tim/.virtualenvs/tmp-c0a4a8105a1aa839/lib/python3.8/site-packages/setuptools/dist.py", line 701, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/home/tim/.virtualenvs/tmp-c0a4a8105a1aa839/lib/python3.8/site-packages/setuptools/config.py", line 121, in parse_configuration
        meta.parse()
      File "/home/tim/.virtualenvs/tmp-c0a4a8105a1aa839/lib/python3.8/site-packages/setuptools/config.py", line 426, in parse
        section_parser_method(section_options)
      File "/home/tim/.virtualenvs/tmp-c0a4a8105a1aa839/lib/python3.8/site-packages/setuptools/config.py", line 399, in parse_section
        self[name] = value
      File "/home/tim/.virtualenvs/tmp-c0a4a8105a1aa839/lib/python3.8/site-packages/setuptools/config.py", line 184, in __setitem__
        value = parser(value)
      File "/home/tim/.virtualenvs/tmp-c0a4a8105a1aa839/lib/python3.8/site-packages/setuptools/config.py", line 515, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/home/tim/.virtualenvs/tmp-c0a4a8105a1aa839/lib/python3.8/site-packages/setuptools/config.py", line 349, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 848, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/tim/code/cockroach-django/django_cockroachdb/__init__.py", line 5, in <module>
        from .utils import check_django_compatability
      File "/home/tim/code/cockroach-django/django_cockroachdb/utils.py", line 1, in <module>
        import django
    ModuleNotFoundError: No module named 'django'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
But after upgrading setuptools to the latest (60.0.2 as of this writing, but also tested with 58.2.0):
```
$ pip install -e ~/code/cockroach-django/
Obtaining file:///home/tim/code/cockroach-django
Installing collected packages: django-cockroachdb
  Running setup.py develop for django-cockroachdb
Successfully installed django-cockroachdb-3.2.2
```

**Comment by timgraham** [comment]
Please reopen if the issue remains.
