### ISSUE TITLE
Can not migrate with cockroachdb

### ISSUE THREAD

**Issue by Azteker** [cockroachdb/django-cockroachdb#262]
Django==3.2.12
django-cockroachdb==3.2

When I run python3 manage.py makemigrations or migrate, I got this error
```
Traceback (most recent call last):
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedColumn: column "type" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 103, in handle
    loader.check_consistent_history(connection)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 294, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    tables = self.connection.introspection.table_names(cursor)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/backends/base/introspection.py", line 52, in table_names
    return get_names(cursor)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/backends/base/introspection.py", line 47, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django_cockroachdb/introspection.py", line 13, in get_table_list
    cursor.execute("SELECT table_name, type FROM [SHOW TABLES]")
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/yxzeng/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column "type" does not exist
```
It is a newly built cockroachdb, I don't have any model with "type" column. This even occurs when I am not migrate for cockroachdb(but have access to it). Running the project is fine though.

**Comment by timgraham** [comment]
Please use the latest version of django-cockroachdb 3.2.x (3.2.3 as of now). What version of CockroachDB are you using? (see [What versions of CockroachDB can I use with each version of Django?](https://github.com/cockroachdb/django-cockroachdb/wiki#what-versions-of-cockroachdb-can-i-use-with-each-version-of-django))

**Comment by Azteker** [comment]
> Please use the latest version of django-cockroachdb 3.2.x (3.2.3 as of now). What version of CockroachDB are you using? (see [What versions of CockroachDB can I use with each version of Django?](https://github.com/cockroachdb/django-cockroachdb/wiki#what-versions-of-cockroachdb-can-i-use-with-each-version-of-django))

Build Tag:    v19.2.4
Build Time:   2020/02/06 21:55:19
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.12.12
C Compiler:   gcc 6.3.0
Build SHA-1:  eb883734bcdafd85d98eb0e49126749bc2cc1284
Build Type:   release

**Comment by timgraham** [comment]
As per [What versions of CockroachDB can I use with each version of Django?](https://github.com/cockroachdb/django-cockroachdb/wiki#what-versions-of-cockroachdb-can-i-use-with-each-version-of-django), Django 3.0.x was the last version to support CockroachDB 19.2.x. CockroachDB 19.2.x also [isn't supported by Cockroach Labs](https://www.cockroachlabs.com/docs/releases/release-support-policy#current-supported-releases).
