### ISSUE TITLE
Test failures due to cockroachdb ordering differences

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#39]
Some tests fail because cockroackdb orders query results differently than other databases. This issue will keep track of those tests and I'll submit a patch to Django to relax the test assertions.
```
======================================================================
FAIL: test_union (filtered_relation.tests.FilteredRelationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/test/testcases.py", line 1229, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/home/tim/code/django/tests/filtered_relation/tests.py", line 200, in test_union
    self.assertSequenceEqual(qs1.union(qs2), [self.author1, self.author2])
AssertionError: Sequences differ: <QuerySet [<Author: Jane>, <Author: Alice>]> != [<Author: Alice>, <Author: Jane>]

First differing element 0:
<Author: Jane>
<Author: Alice>

- <QuerySet [<Author: Jane>, <Author: Alice>]>
+ [<Author: Alice>, <Author: Jane>]
```

**Comment by jordanlewis** [comment]
These are caused by union in particular, which we don't bother to keep in-order when the SQL spec doesn't mandate it. I agree with your plan to submit a patch to the Django test suite, since technically the results here are within spec - there's no order by clause on the query, presumably.

**Comment by timgraham** [comment]
```
======================================================================
FAIL: test_distinct_on_with_annotation (annotations.tests.NonAggregateAnnotationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/test/testcases.py", line 1229, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/home/tim/code/django/tests/annotations/tests.py", line 213, in test_distinct_on_with_annotation
    self.assertSequenceEqual(lengths, [3, 7, 8])
AssertionError: Sequences differ: <QuerySet [8, 7, 3]> != [3, 7, 8]

First differing element 0:
8
3

- <QuerySet [8, 7, 3]>
+ [3, 7, 8]
```

**Comment by timgraham** [comment]
```
======================================================================
FAIL: test_window_expression_within_subquery (expressions_window.tests.WindowFunctionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/expressions_window/tests.py", line 694, in test_window_expression_within_subquery
    {'department': 'Management', 'salary': 100000}
AssertionError: Sequences differ: <QuerySet [{'department': 'Accounting', '[187 chars]00}]> != [{'department': 'Accounting', 'salary': 5[176 chars]000}]

First differing element 1:
{'department': 'IT', 'salary': 60000}
{'department': 'Sales', 'salary': 55000}

- <QuerySet [{'department': 'Accounting', 'salary': 50000}, {'department': 'IT', 'salary': 60000}, {'department': 'Management', 'salary': 100000}, {'department': 'Marketing', 'salary': 40000}, {'department': 'Sales', 'salary': 55000}]>
+ [{'department': 'Accounting', 'salary': 50000},
+  {'department': 'Sales', 'salary': 55000},
+  {'department': 'Marketing', 'salary': 40000},
+  {'department': 'IT', 'salary': 60000},
+  {'department': 'Management', 'salary': 100000}]
```

**Comment by timgraham** [comment]
```
======================================================================
FAIL: test_fkey_aggregate (aggregation.tests.AggregateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/aggregation/tests.py", line 435, in test_fkey_aggregate
    self.assertEqual(explicit, implicit)
AssertionError: Lists differ: [<Author: James Bennett>, <Author: Paul Bissex>, <A[174 chars]ell>] != [<Author: Paul Bissex>, <Author: Peter Norvig>, <Au[174 chars]ell>]

First differing element 0:
<Author: James Bennett>
<Author: Paul Bissex>

- [<Author: James Bennett>,
-  <Author: Paul Bissex>,
? ^

+ [<Author: Paul Bissex>,
? ^

+  <Author: Peter Norvig>,
-  <Author: Wesley J. Chun>,
-  <Author: Adrian Holovaty>,
   <Author: Jacob Kaplan-Moss>,
   <Author: Brad Dayley>,
+  <Author: James Bennett>,
   <Author: Jeffrey Forcier>,
-  <Author: Peter Norvig>,
+  <Author: Adrian Holovaty>,
+  <Author: Wesley J. Chun>,
   <Author: Stuart Russell>]
```

**Comment by timgraham** [comment]
Patch is submitted upstream to Django: https://github.com/django/django/pull/12077.

For what it's worth, the test from this issue's description (`filtered_relation.tests.FilteredRelationTests.test_union`) no longer seems to be an issue so I didn't include that.
