### ISSUE TITLE
extract() function doesn't respect active time zone

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#47]
When no timezone is active:
```sql
> CREATE TABLE "timezones_event" ("id" integer NOT NULL PRIMARY KEY DEFAULT unique_rowid(), "dt" timestamptz NOT NULL);
> INSERT INTO "timezones_event" ("dt") VALUES ('2011-01-01T01:30:00+00:00'::timestamptz);
> SELECT dt, EXTRACT(hour FROM dt) FROM timezones_event;
             dt             | extract  
+---------------------------+---------+
  2011-01-01 01:30:00+00:00 |       1  
```
But when a timezone is active ('Africa/Nairobi' is UTC+3), the extracted value isn't localized:
```sql
> SET TIME ZONE 'Africa/Nairobi';
> SELECT dt, EXTRACT(hour FROM dt) FROM timezones_event;
             dt             | extract  
+---------------------------+---------+
  2011-01-01 04:30:00+03:00 |       1  
(1 row)
```
I believe this is a bug in cockroachdb.

The relevant Django test:

```
======================================================================
FAIL: test_extract_func (db_functions.datetime.test_extract_trunc.DateFunctionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/db_functions/datetime/test_extract_trunc.py", line 204, in test_extract_func
    lambda m: (m.start_datetime, m.extracted)
  File "/home/tim/code/django/django/test/testcases.py", line 1056, in assertQuerysetEqual
    return self.assertEqual(list(items), values, msg=msg)
AssertionError: Lists differ: [(dat[42 chars]1), 19), (datetime.datetime(2016, 6, 15, 14, 10, 50, 123), 19)] != [(dat[42 chars]1), 14), (datetime.datetime(2016, 6, 15, 14, 10, 50, 123), 14)]

First differing element 0:
(datetime.datetime(2015, 6, 15, 14, 30, 50, 321), 19)
(datetime.datetime(2015, 6, 15, 14, 30, 50, 321), 14)

- [(datetime.datetime(2015, 6, 15, 14, 30, 50, 321), 19),
?                                                     ^

+ [(datetime.datetime(2015, 6, 15, 14, 30, 50, 321), 14),
?                                                     ^

-  (datetime.datetime(2016, 6, 15, 14, 10, 50, 123), 19)]
?                                                     ^

+  (datetime.datetime(2016, 6, 15, 14, 10, 50, 123), 14)]
?                                                     ^
```

**Comment by rafiss** [comment]
I believe this should be fixed by https://github.com/cockroachdb/cockroach/pull/42267 which will be in the next 19.2 release.

**Comment by timgraham** [comment]
I'm seeing the same failure with CockroachDB CCL v20.1.0-alpha.00000000-919-ge78a2b6 (x86_64-unknown-linux-gnu, built 2019/11/16), and the steps in the issue description also reproduce the issue.

**Comment by jordanlewis** [comment]
@otan PTAL

**Comment by otan** [comment]
Haha I literally just noticed this when trying to do `TimeTZ`, I will take a look :)
