### ISSUE TITLE
Incorrect interval math on date columns when a time zone is set

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#53]
When no timezone is active:
```sql
> CREATE TABLE "example" ("id" integer NOT NULL PRIMARY KEY DEFAULT unique_rowid(), "a" date NOT NULL, "b" date NOT NULL);
> INSERT INTO "example" ("a", "b") VALUES ('2011-01-01'::date, '2011-01-01'::date);
> SELECT * FROM "example" WHERE "a" <= ("b" + '0 days 0.000000 seconds'::interval);
          id         |             a             |             b              
+--------------------+---------------------------+---------------------------+
  497332820171915265 | 2011-01-01 00:00:00+00:00 | 2011-01-01 00:00:00+00:00
```
But when a timezone is active, no results are returned:
```sql
> SET TIME ZONE 'America/Chicago';
> SELECT * FROM "example" WHERE "a" <= ("b" + '0 days 0.000000 seconds'::interval);
  id | a | b  
+----+---+---+
(0 rows)

```
I believe this is a bug in cockroachdb.

The relevant Django test:

```
======================================================================
FAIL: test_date_comparison (expressions.tests.FTimeDeltaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/home/tim/code/django/tests/expressions/tests.py", line 1197, in test_date_comparison
    self.assertEqual(test_set, self.expnames[:i + 1])
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 1045, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 1027, in assertSequenceEqual
    self.fail(msg)
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: [] != ['e0']

Second list contains 1 additional elements.
First extra element 0:
'e0'

- []
+ ['e0']
```

**Comment by rafiss** [comment]
It might potentially relate to this: https://github.com/cockroachdb/cockroach/issues/35874

**Comment by timgraham** [comment]
This test is working on the cockroach master branch. Perhaps it was fixed as a side effect of something else.

**Comment by timgraham** [comment]
The test passes with v20.1.0-alpha20191216 but fails with today's build of CockroachDB master. \cc @otan (possibly something you have expertise about)

**Comment by otan** [comment]
this passes on master for me :o

**Comment by otan** [comment]
(at least, the example posted above)

**Comment by timgraham** [comment]
Apologies, the issue is different: https://github.com/cockroachdb/django-cockroachdb/issues/120.
