### ISSUE TITLE
unsupported queries: aliasing EXISTS() or subquery fails with "column does not exist"

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#82]
These queries fail:
```sql
SELECT 
    EXISTS(
        SELECT U0."id", U0."isbn", U0."name", U0."pages", U0."rating", U0."price", U0."contact_id", U0."publisher_id", U0."pubdate" FROM "aggregation_book" U0
        WHERE (U0."pages" > 800 AND U0."publisher_id" = "aggregation_publisher"."id")
    ) AS "exists1",
    COUNT(*) AS "total" 
FROM "aggregation_publisher"
GROUP BY "exists1";
```
Django test failure:
```
======================================================================
ERROR: test_group_by_exists_annotation (aggregation.tests.AggregateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "exists1" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/django/django/test/testcases.py", line 1247, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/home/tim/code/django/tests/aggregation/tests.py", line 1172, in test_group_by_exists_annotation
    self.assertEqual(dict(has_long_books_breakdown), {True: 2, False: 3})
  File "/home/tim/code/django/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/home/tim/code/django/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tim/code/django/django/db/models/query.py", line 146, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1056, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1104, in execute_sql
    cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tim/code/django/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tim/code/django/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/code/django/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "exists1" does not exist
```
Second failure:
```sql
SELECT 
    (
        SELECT COUNT(U0."id") AS "count" FROM "aggregation_book" U0
        WHERE (U0."pages" > 400 AND U0."publisher_id" = "aggregation_publisher"."id")
        GROUP BY U0."publisher_id"
    ) AS "subquery1",
    COUNT(*) AS "total"
FROM "aggregation_publisher"
GROUP BY "subquery1";
```
Django test failure:
```
======================================================================
ERROR: test_group_by_subquery_annotation (aggregation.tests.AggregateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "subquery1" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/django/django/test/testcases.py", line 1247, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/home/tim/code/django/tests/aggregation/tests.py", line 1157, in test_group_by_subquery_annotation
    self.assertEqual(dict(long_books_count_breakdown), {None: 1, 1: 4})
  File "/home/tim/code/django/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/home/tim/code/django/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tim/code/django/django/db/models/query.py", line 146, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1056, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1104, in execute_sql
    cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tim/code/django/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tim/code/django/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/code/django/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "subquery1" does not exist
```

**Comment by rafiss** [comment]
The aliases are now supported in the bleeding edge build.

**Comment by timgraham** [comment]
Confirmed.
