### ISSUE TITLE
unsupported query: ALTER SEQUENCE ... OWNED BY ...

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/django-cockroachdb#83]
Django 3.0 includes [a bug fix](https://github.com/django/django/commit/f944cb3d3bc17a97216f8990ff3bb4bee14b6f6b) to preserve the sequence owner when altering an AutoField/BigAutoField on PostgreSQL.

However, this SQL isn't supported by cockroachdb...
```
======================================================================
ERROR: test_alter_autofield_pk_to_bigautofield_pk_sequence_owner (schema.tests.SchemaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.FeatureNotSupported: at or near "EOF": syntax error: unimplemented: this syntax
DETAIL:  source SQL:
ALTER SEQUENCE "schema_author_id_seq" OWNED BY "schema_author"."id"
                                                                   ^
HINT:  You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/26382


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/django/tests/schema/tests.py", line 1194, in test_alter_autofield_pk_to_bigautofield_pk_sequence_owner
    editor.alter_field(Author, old_field, new_field, strict=True)
  File "/home/tim/code/django/django/db/backends/base/schema.py", line 565, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/tim/code/cockroach-django/cockroach/django/schema.py", line 37, in _alter_field
    new_db_params, strict,
  File "/home/tim/code/django/django/db/backends/base/schema.py", line 739, in _alter_field
    self.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tim/code/django/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tim/code/django/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/code/django/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.NotSupportedError: at or near "EOF": syntax error: unimplemented: this syntax
DETAIL:  source SQL:
ALTER SEQUENCE "schema_author_id_seq" OWNED BY "schema_author"."id"
                                                                   ^
HINT:  You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/26382
```
That said, I don't think Django needs to manage any sequences because `unique_rowid()` is used for AutoField. Is that correct?

**Comment by rafiss** [comment]
Link to cockroachdb issue: https://github.com/cockroachdb/cockroach/issues/26382

It does seem that `unique_rowid()` should be used for AutoField, but I haven't confirmed this yet.
